// Parameters: dialog enum ID, (unused), lines per box, left offset, width

DEFINE_DIALOG(DIALOG_000, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_001, 1, 4, 95, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_002, 1, 4, 95, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_003, 1, 5, 95, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_004, 1, 3, 95, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_005, 1, 4, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_006, 1, 4, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_007, 1, 6, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_008, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_009, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_010, 1, 3, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_011, 1, 3, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_012, 1, 3, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_013, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_014, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_015, 1, 4, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_016, 1, 4, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_017, 1, 4, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_018, 1, 4, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_019, 1, 2, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_020, 1, 5, 95, 150, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_021, 1, 4, 52, 200, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_022, 1, 3, 95, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_023, 1, 3, 95, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_024, 1, 3, 95, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_025, 1, 3, 95, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_026, 1, 3, 95, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_027, 1, 3, 95, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_028, 1, 3, 95, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_029, 1, 4, 95, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_030, 1, 4, 52, 200, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_031, 1, 3, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_032, 1, 4, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_033, 1, 4, 52, 200, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_034, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_035, 1, 4, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_036, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_037, 1, 3, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_038, 1, 3, 95, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_039, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_040, 1, 3, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_041, 1, 4, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_042, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_043, 1, 4, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_044, 1, 5, 95, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_045, 1, 5, 95, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_046, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_047, 1, 3, 95, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_048, 1, 4, 52, 200, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_049, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_050, 1, 4, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_051, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_052, 1, 4, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_053, 1, 4, 52, 200, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_054, 1, 4, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_055, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_056, 1, 3, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_057, 1, 4, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_058, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_059, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_060, 1, 4, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_061, 1, 6, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_062, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_063, 1, 4, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_064, 1, 4, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_065, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_066, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_067, 1, 4, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_068, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_069, 1, 3, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_070, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_071, 1, 4, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_072, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_073, 1, 5, 95, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_074, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_075, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_076, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_077, 1, 3, 150, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_078, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_079, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_080, 1, 3, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_081, 1, 6, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_082, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_083, 1, 4, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_084, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_085, 1, 4, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_086, 1, 3, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_087, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_088, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_089, 1, 4, 95, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_090, 1, 6, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_091, 1, 3, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_092, 1, 3, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_093, 1, 4, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_094, 1, 3, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_095, 1, 3, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_096, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_097, 1, 4, 52, 200, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_098, 1, 3, 95, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_099, 1, 3, 95, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_100, 1, 4, 95, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_101, 1, 5, 95, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_102, 1, 4, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_103, 1, 4, 95, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_104, 1, 6, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_105, 1, 3, 95, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_106, 1, 3, 95, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_107, 1, 3, 95, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_108, 1, 3, 95, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_109, 1, 4, 95, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_110, 1, 3, 95, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_111, 1, 3, 95, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_112, 1, 4, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_113, 1, 6, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_114, 1, 4, 95, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_115, 1, 5, 95, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_116, 1, 5, 95, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_117, 1, 3, 95, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_118, 1, 5, 95, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_119, 1, 4, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_120, 1, 4, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_121, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_122, 1, 6, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_123, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_124, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_125, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_126, 1, 6, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_127, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_128, 1, 4, 95, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_129, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_130, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_131, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_132, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_133, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_134, 1, 4, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_135, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_136, 1, 4, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_137, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_138, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_139, 1, 6, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_140, 1, 6, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_141, 1, 5, 150, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_142, 1, 5, 150, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_143, 1, 6, 150, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_144, 1, 5, 150, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_145, 1, 4, 150, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_146, 1, 6, 150, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_147, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_148, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_149, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))
DEFINE_DIALOG(DIALOG_149, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_150, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_151, 1, 4, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_152, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_153, 1, 4, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_154, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_155, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_156, 1, 4, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_157, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_158, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_159, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_160, 1, 4, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_161, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_162, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_163, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_164, 1, 4, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_165, 1, 4, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_166, 1, 6, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_167, 1, 4, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_168, 1, 4, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))

DEFINE_DIALOG(DIALOG_169, 1, 5, 30, 205, _("TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP TEMP"))
