#ifndef MARIO_ANIMATION_IDS_H
#define MARIO_ANIMATION_IDS_H

/* Mario Animation IDs (with the names from anime.s) */

enum MarioAnimID {
    /* 0x00 */ MARIO_ANIM_SLOW_LEDGE_GRAB,                      // animMarioAscend
    /* 0x01 */ MARIO_ANIM_FALL_OVER_BACKWARDS,                  // animMarioBackDown
    /* 0x02 */ MARIO_ANIM_BACKWARD_AIR_KB,                      // animMarioJumpBackDown
    /* 0x03 */ MARIO_ANIM_DYING_ON_BACK,                        // animMarioBackDownEnd
    /* 0x04 */ MARIO_ANIM_CLIMB_UP_POLE,                        // animMarioBarClimb
    /* 0x05 */ MARIO_ANIM_GRAB_POLE_SHORT,                      // animMarioBarHang
    /* 0x06 */ MARIO_ANIM_GRAB_POLE_SWING_PART1,                // animMarioBarJumping
    /* 0x07 */ MARIO_ANIM_GRAB_POLE_SWING_PART2,                // animMarioBarJumpEnd
    /* 0x08 */ MARIO_ANIM_IDLE_ON_POLE,                         // animMarioBarWaiting
    /* 0x09 */ MARIO_ANIM_A_POSE,                               // animMarioBaseData
    /* 0x0A */ MARIO_ANIM_SKID_ON_GROUND,                       // animMarioBraking
    /* 0x0B */ MARIO_ANIM_STOP_SKID,                            // animMarioBrakeEnd
    /* 0x0C */ MARIO_ANIM_AIRBORNE_ON_STOMACH,                  // animMarioCannonFly
    /* 0x0D */ MARIO_ANIM_WALK_WITH_LIGHT_OBJ,                  // animMarioCarryJogging
    /* 0x0E */ MARIO_ANIM_RUN_WITH_LIGHT_OBJ,                   // animMarioCarryRunning
    /* 0x0F */ MARIO_ANIM_SLOW_WALK_WITH_LIGHT_OBJ,             // animMarioCarryWalking
    /* 0x10 */ MARIO_ANIM_CLIMB_DOWN_LEDGE,                     // animMarioDescend
    /* 0x11 */ MARIO_ANIM_STAND_UP_FROM_LAVA_BOOST,             // animMarioFireJumpEnd
    /* 0x12 */ MARIO_ANIM_FIRE_LAVA_BURN,                       // animMarioFireJumping
    /* 0x13 */ MARIO_ANIM_WING_CAP_FLY,                         // animMarioFlight
    /* 0x14 */ MARIO_ANIM_WATER_IDLE_WITH_OBJ,                  // animMarioFloatHold
    /* 0x15 */ MARIO_ANIM_WATER_IDLE,                           // animMarioFloating
    /* 0x16 */ MARIO_ANIM_WATER_ANALOG_SWIMMING,                // animMarioFloatMoving
    /* 0x17 */ MARIO_ANIM_WATER_PICK_UP_OBJ,                    // animMarioFloatTake
    /* 0x18 */ MARIO_ANIM_WATER_THROW_OBJ,                      // animMarioFloatThrow
    /* 0x19 */ MARIO_ANIM_HANG_ON_OWL,                          // animMarioFlying
    /* 0x1A */ MARIO_ANIM_LAND_ON_STOMACH,                      // animMarioForeDown
    /* 0x1B */ MARIO_ANIM_AIR_FORWARD_KB,                       // animMarioJumpForeDown
    /* 0x1C */ MARIO_ANIM_DYING_ON_STOMACH,                     // animMarioForeDownEnd
    /* 0x1D */ MARIO_ANIM_DYING_FALL_OVER,                      // animMarioGiddyDown
    /* 0x1E */ MARIO_ANIM_IDLE_ON_LEDGE,                        // animMarioHanging
    /* 0x1F */ MARIO_ANIM_FAST_LEDGE_GRAB,                      // animMarioHangJump
    /* 0x20 */ MARIO_ANIM_GROUND_POUND_LANDING,                 // animMarioHipAttackEnd
    /* 0x21 */ MARIO_ANIM_START_GROUND_POUND,                   // animMarioHipAttackStart
    /* 0x22 */ MARIO_ANIM_GROUND_POUND,                         // animMarioHipAttacking
    /* 0x23 */ MARIO_ANIM_IDLE_WITH_LIGHT_OBJ,                  // animMarioHolding
    /* 0x24 */ MARIO_ANIM_JUMP_LAND_WITH_LIGHT_OBJ,             // animMarioHoldJumpEnd
    /* 0x25 */ MARIO_ANIM_JUMP_WITH_LIGHT_OBJ,                  // animMarioHoldJumping
    /* 0x26 */ MARIO_ANIM_FALL_LAND_WITH_LIGHT_OBJ,             // animMarioHoldLandEnd
    /* 0x27 */ MARIO_ANIM_FALL_WITH_LIGHT_OBJ,                  // animMarioHoldLanding
    /* 0x28 */ MARIO_ANIM_FALL_FROM_SLIDING_WITH_LIGHT_OBJ,     // animMarioHoldSlipLanding
    /* 0x29 */ MARIO_ANIM_SLIDING_ON_BOTTOM_WITH_LIGHT_OBJ,     // animMarioHoldSlipping
    /* 0x2A */ MARIO_ANIM_STAND_UP_FROM_SLIDING_WITH_LIGHT_OBJ, // animMarioHoldSlipEnd
    /* 0x2B */ MARIO_ANIM_WALKING,                              // animMarioJogging
    /* 0x2C */ MARIO_ANIM_FORWARD_FLIP,                         // animMarioJumpBack        (unused)
    /* 0x2D */ MARIO_ANIM_LAND_FROM_DOUBLE_JUMP,                // animMarioJumpEnd2
    /* 0x2E */ MARIO_ANIM_DOUBLE_JUMP_FALL,                     // animMarioJumpFall
    /* 0x2F */ MARIO_ANIM_SINGLE_JUMP,                          // animMarioJumping
    /* 0x30 */ MARIO_ANIM_LAND_FROM_SINGLE_JUMP,                // animMarioJumpEnd
    /* 0x31 */ MARIO_ANIM_DOUBLE_JUMP_RISE,                     // animMarioJumpStep2
    /* 0x32 */ MARIO_ANIM_START_FORWARD_SPINNING,               // animMarioJumpStep3       (unused)
    /* 0x33 */ MARIO_ANIM_THROW_LIGHT_OBJECT,                   // animMarioJumpThrow
    /* 0x34 */ MARIO_ANIM_GENERAL_FALL,                         // animMarioLanding
    /* 0x35 */ MARIO_ANIM_GENERAL_LAND,                         // animMarioLandEnd
    /* 0x36 */ MARIO_ANIM_BEING_GRABBED,                        // animMarioLifted
    /* 0x37 */ MARIO_ANIM_GRAB_HEAVY_OBJECT,                    // animMarioLifting
    /* 0x38 */ MARIO_ANIM_SLOW_LAND_FROM_DIVE,                  // animMarioLostStandup
    /* 0x39 */ MARIO_ANIM_FLY_FROM_CANNON,                      // animMarioMantFlying
    /* 0x3A */ MARIO_ANIM_PULL_DOOR_WALK_IN,                    // animMarioOpenDoor1
    /* 0x3B */ MARIO_ANIM_PUSH_DOOR_WALK_IN,                    // animMarioOpenDoor2
    /* 0x3C */ MARIO_ANIM_GROUND_THROW,                         // animMarioPitching
    /* 0x3D */ MARIO_ANIM_GROUND_KICK,                          // animMarioPowerKick
    /* 0x3E */ MARIO_ANIM_FIRST_PUNCH,                          // animMarioPunchBase
    /* 0x3F */ MARIO_ANIM_FIRST_PUNCH_FAST,                     // animMarioPunchEnd
    /* 0x40 */ MARIO_ANIM_PICK_UP_LIGHT_OBJ,                    // animMarioPunchTake
    /* 0x41 */ MARIO_ANIM_PUSHING,                              // animMarioPushing
    /* 0x42 */ MARIO_ANIM_PLACE_LIGHT_OBJ,                      // animMarioPutting
    /* 0x43 */ MARIO_ANIM_FORWARD_SPINNING,                     // animMarioRolling
    /* 0x44 */ MARIO_ANIM_BACKWARD_SPINNING,                    // animMarioBackRolling
    /* 0x45 */ MARIO_ANIM_RUNNING,                              // animMarioRunning
    /* 0x46 */ MARIO_ANIM_RUNNING_UNUSED,                       // animMarioTurnCont        (unused)
    /* 0x47 */ MARIO_ANIM_SOFT_BACK_KB,                         // animMarioSafeBackDown
    /* 0x48 */ MARIO_ANIM_SOFT_FRONT_KB,                        // animMarioSafeForeDown
    /* 0x49 */ MARIO_ANIM_BACKWARD_KB,                          // animMarioShortBackDown
    /* 0x4A */ MARIO_ANIM_FORWARD_KB,                           // animMarioShortForeDown
    /* 0x4B */ MARIO_ANIM_IDLE_HEAVY_OBJ,                       // animMarioShoulder
    /* 0x4C */ MARIO_ANIM_STAND_AGAINST_WALL,                   // animMarioSideWait
    /* 0x4D */ MARIO_ANIM_SIDESTEP_LEFT,                        // animMarioSideWalkL
    /* 0x4E */ MARIO_ANIM_SIDESTEP_RIGHT,                       // animMarioSideWalkR
    /* 0x4F */ MARIO_ANIM_START_SLEEP_IDLE,                     // animMarioSleeping1
    /* 0x50 */ MARIO_ANIM_START_SLEEP_SCRATCH,                  // animMarioSleeping2
    /* 0x51 */ MARIO_ANIM_START_SLEEP_YAWN,                     // animMarioSleeping3
    /* 0x52 */ MARIO_ANIM_START_SLEEP_SITTING,                  // animMarioSleeping4
    /* 0x53 */ MARIO_ANIM_SLEEP_IDLE,                           // animMarioSleeping5
    /* 0x54 */ MARIO_ANIM_DIVE,                                 // animMarioSlideCatch
    /* 0x55 */ MARIO_ANIM_SLIDE_DIVE,                           // animMarioSlipBack
    /* 0x56 */ MARIO_ANIM_STOP_SLIDE_LIGHT_OBJ,                 // animMarioSlideStandup
    /* 0x57 */ MARIO_ANIM_SLIDE_MOTIONLESS,                     // animMarioSlip
    /* 0x58 */ MARIO_ANIM_STOP_SLIDE,                           // animMarioSlipEnd
    /* 0x59 */ MARIO_ANIM_FALL_FROM_SLIDE,                      // animMarioSlipLanding
    /* 0x5A */ MARIO_ANIM_TIPTOE,                               // animMarioSoftStep
    /* 0x5B */ MARIO_ANIM_TWIRL_LAND,                           // animMarioSpinJpEnd
    /* 0x5C */ MARIO_ANIM_TWIRL,                                // animMarioSpinJumping
    /* 0x5D */ MARIO_ANIM_START_TWIRL,                          // animMarioSpinJpStart
    /* 0x5E */ MARIO_ANIM_STOP_CROUCHING,                       // animMarioSquatEnd
    /* 0x5F */ MARIO_ANIM_START_CROUCHING,                      // animMarioSquatStart
    /* 0x60 */ MARIO_ANIM_CROUCHING,                            // animMarioSquatWaiting
    /* 0x61 */ MARIO_ANIM_CRAWLING,                             // animMarioSquatWalking
    /* 0x62 */ MARIO_ANIM_STOP_CRAWLING,                        // animMarioSquatWalkEnd
    /* 0x63 */ MARIO_ANIM_START_CRAWLING,                       // animMarioSquatWalkStart
    /* 0x64 */ MARIO_ANIM_BACKWARDS_WATER_KB,                   // animMarioSwimBackDown
    /* 0x65 */ MARIO_ANIM_FLUTTERKICK_WITH_OBJ,                 // animMarioSwimCarry
    /* 0x66 */ MARIO_ANIM_DROWNING_PART1,                       // animMarioSwimDown1
    /* 0x67 */ MARIO_ANIM_DROWNING_PART2,                       // animMarioSwimDown2
    /* 0x68 */ MARIO_ANIM_WATER_DYING,                          // animMarioSwimDownEnd
    /* 0x69 */ MARIO_ANIM_WATER_FORWARD_KB,                     // animMarioSwimForeDown
    /* 0x6A */ MARIO_ANIM_STOP_GRAB_OBJ_WATER,                  // animMarioSwimHold
    /* 0x6B */ MARIO_ANIM_SWIM_PART1,                           // animMarioSwimming1
    /* 0x6C */ MARIO_ANIM_SWIM_PART2,                           // animMarioSwimming2
    /* 0x6D */ MARIO_ANIM_FLUTTERKICK,                          // animMarioSwimming3    
    /* 0x6E */ MARIO_ANIM_WATER_ACTION_END,                     // animMarioSwimStop
    /* 0x6F */ MARIO_ANIM_WATER_STAR_DANCE,                     // animMarioSwimWinDemo
    /* 0x70 */ MARIO_ANIM_GRAB_BOWSER,                          // animMarioSwingStart
    /* 0x71 */ MARIO_ANIM_SWINGING_BOWSER,                      // animMarioSwingAttack
    /* 0x72 */ MARIO_ANIM_RELEASE_BOWSER,                       // animMarioSwingDown
    /* 0x73 */ MARIO_ANIM_HOLDING_BOWSER,                       // animMarioSwingWait
    /* 0x74 */ MARIO_ANIM_HEAVY_THROW,                          // animMarioThrowing
    /* 0x75 */ MARIO_ANIM_WALK_PANTING,                         // animMarioTiredWaiting
    /* 0x76 */ MARIO_ANIM_WALK_WITH_HEAVY_OBJ,                  // animMarioTransfer
    /* 0x77 */ MARIO_ANIM_TURNING_PART1,                        // animMarioTurning
    /* 0x78 */ MARIO_ANIM_TURNING_PART2,                        // animMarioTurnEnd
    /* 0x79 */ MARIO_ANIM_SLIDEFLIP_LAND,                       // animMarioUJumpEnd
    /* 0x7A */ MARIO_ANIM_SLIDEFLIP,                            // animMarioUJumping
    /* 0x7B */ MARIO_ANIM_FIRST_PERSON,                         // animMarioViewing
    /* 0x7C */ MARIO_ANIM_IDLE_HEAD_LEFT,                       // animMarioWaiting1
    /* 0x7D */ MARIO_ANIM_IDLE_HEAD_RIGHT,                      // animMarioWaiting2
    /* 0x7E */ MARIO_ANIM_IDLE_HEAD_CENTER,                     // animMarioWaiting3
    /* 0x7F */ MARIO_ANIM_WAKE_FROM_SLEEP,                      // animMarioWakeup
    /* 0x80 */ MARIO_ANIM_START_TIPTOE,                         // animMarioWalking
    /* 0x81 */ MARIO_ANIM_SLIDEJUMP,                            // animMarioWallJump
    /* 0x82 */ MARIO_ANIM_START_WALLKICK,                       // animMarioWallStay
    /* 0x83 */ MARIO_ANIM_STAR_DANCE                            // animMarioWinDemoA
};

#endif // MARIO_ANIMATION_IDS_H
